#!/bin/bash
# post setup
#
# Johannes Winkelmann, jw at tks6 dot net

ROOT=$1
DB=$ROOT/var/lib/pkg/db

## those values should be changed:
TMPDB=$DB.tmp
BACKUPDB=$DB.backup
PKGADD="pkgadd"
PKGRM="pkgrm"
MV="mv"


is_installed() {
    printf "%s" $(pkginfo -r $ROOT -i | gawk -v r="^$1\$" '$1 ~ r {print $1}')
}


rename_packages() {
    if [ -z "$1" ]; then
	return
    fi
    pkg=$@

    filter="sed "
    runfilter="no"
    for tuple in $@; do
	split=($(echo $tuple|sed -e 's|:| |'))
	if [ -n "${split[1]}" ] && [ `is_installed ${split[0]}` ]; then
	    echo "Package renamed:  ${split[0]} -> ${split[1]}"
	    filter="$filter -e 's|^${split[0]}$|${split[1]}|'"
	    runfilter="yes"
	fi
    done
    if [ "$runfilter" = "no" ]; then
	return
    fi

    :> $TMPDB
    if [ -f $DB ]; then
	nextIsName=1
	cat $DB|while read l; do
	    if [ $nextIsName -eq 1 ]; then
		nextIsName=0
		echo $l|eval $filter >> $TMPDB
	    else
		if [ "$l" = "" ]; then
		    nextIsName=1
		fi
		echo $l >> $TMPDB
	    fi
	done
    fi

    $MV $DB $BACKUPDB
    $MV $TMPDB $DB
}


remove_packages() {
    for package in $@; do
	if [ `is_installed $package` ]; then
	    echo "Package removed:  $package"
            $PKGRM -r $ROOT $package
	fi
    done
}

inject_packages() {
    for package in $@; do
    pkg="`find core opt xorg \( -name \"${package}#*.pkg.tar.gz\" -o -name \"${package}#*.pkg.tar.bz2\" -o -name \"${package}#*.pkg.tar.xz\" \)&2> /dev/null`"
	if [ -z "$pkg" ]; then
		echo "  ERROR: package $package not found on ISO"
	else
		if [ -z `is_installed $package` ]; then
		    echo "Package injected: $package"
			$PKGADD -r $ROOT -f $pkg
		else
			echo "Package upgraded: $package"
			$PKGADD -r $ROOT -u -f $pkg
		fi
	fi
    done
}

####################

if [ -z "$1" ]; then
    echo "Usage: $0 <root>"
    exit -1
fi


##### # 3.6 -> 3.7 #####
echo "* CRUX 3.6 -> 3.7 setup-helper"

rename_packages pkg-config:pkgconf

inject_packages dumb_runtime_dir

# moved from opt to core
inject_packages libpcre2 cmake meson ninja

# new deps of core/cmake
inject_packages jsoncpp libuv lzlib rhash

# new deps of core/iptables
inject_packages nftables libedit jansson libnftnl libmnl


if [ `is_installed xfsprogs` ]; then
	inject_packages inih liburcu
fi

if [ `is_installed ppp` ]; then
	inject_packages libpcap
fi

if [ `is_installed shared-mime-info` ]; then
	inject_packages itstool python3-libxml2
fi

if [ `is_installed xorg-server` ]; then
	inject_packages nettle xorg-libxcvt
fi

if [ `is_installed nghttp2-libs` ]; then
	rename_packages nghttp2-libs:libnghttp2
else
	inject_packages libnghttp2
fi

if [ `is_installed atk` ]; then
	remove_packages atk
	inject_packages at-spi2-core
fi

if [ `is_installed at-spi2-atk` ]; then
	remove_packages at-spi2-atk
	inject_packages at-spi2-core
fi

if [ `is_installed mesa` ]; then
	inject_packages glslang spirv-headers spirv-tools
fi
